# Project information
site_name: Electronic dices STC
site_description: Electronic dices STC document
site_author: hktkzyx
copyright: 
  Copyright &copy; 2022 hktkzyx.
  Content on this site is licensed under CC BY 4.0.

# Repository
repo_name: hktkzyx/electronic-dices-stc-hardware
repo_url: https://github.com/hktkzyx/electronic-dices-stc-hardware

# Configuration
nav:
  - Home: README.md
theme: 
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
plugins:
  - search
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hktkzyx
    - icon: material/email
      link: mailto:<hktkzyx@yeah.net>
    
  
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - md_in_html # Images with caption
  - meta
  - tables
  # Code block
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # MathJax
  - pymdownx.arithmatex:
      generic: true

# MathJax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js